FROM node:22-alpine
WORKDIR /app

# Copiar archivos de dependencias e instalar
COPY package*.json ./
RUN npm install

# Copiar todo el código (esto congela el código para el test)
COPY . .

# Declarar argumentos de construcción (Build Args) para Vite
ARG VITE_API_URL
ARG VITE_APP_ENV

# Convertir los argumentos en variables de entorno del contenedor
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_APP_ENV=$VITE_APP_ENV

EXPOSE 5173

# Correr el servidor de desarrollo de Vite
CMD ["npm", "run", "dev", "--", "--host"]