export const orders = [
  {
    id: "#RP001",
    date: "2024-01-10",
    status: "Entregado",
    total: 45,
    currency: "$",
    action: "VER DETALLES",
  },
  {
    id: "#RP002",
    date: "2024-01-15",
    status: "Pendiente",
    total: 120,
    currency: "$",
    action: "RASTREAR",
  },
  {
    id: "#RP003",
    date: "2024-02-01",
    status: "Enviado",
    total: 32,
    currency: "$",
    action: "RASTREAR",
  },
  {
    id: "#RP004",
    date: "2024-02-12",
    status: "Cancelado",
    total: 85,
    currency: "$",
    action: "VER DETALLES",
  },
  {
    id: "#RP005",
    date: "2024-02-28",
    status: "Entregado",
    total: 210,
    currency: "$",
    action: "VER DETALLES",
  },
  {
    id: "#RP006",
    date: "2024-03-05",
    status: "Procesando",
    total: 15,
    currency: "$",
    action: "RASTREAR",
  },
  {
    id: "#RP007",
    date: "2024-03-10",
    status: "Entregado",
    total: 67,
    currency: "$",
    action: "VER DETALLES",
  },
  {
    id: "#RP008",
    date: "2024-03-22",
    status: "Pendiente",
    total: 93,
    currency: "$",
    action: "RASTREAR",
  },
  {
    id: "#RP009",
    date: "2024-04-02",
    status: "Enviado",
    total: 54,
    currency: "$",
    action: "RASTREAR",
  },
  {
    id: "#RP010",
    date: "2024-04-15",
    status: "Entregado",
    total: 110,
    currency: "$",
    action: "VER DETALLES",
  },
  {
    id: "#RP011",
    date: "2024-04-20",
    status: "Procesando",
    total: 28,
    currency: "$",
    action: "VER DETALLES",
  },
];